import { readFile } from 'node:fs/promises'
import AxeBuilder from '@axe-core/playwright'
import { expect, test } from '@playwright/test'

test('library and weighted dice work in demo mode', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Biblioteca privada' })).toBeVisible()
  await expect(page.getByTestId('shell-pulse')).toContainText('Biblioteca')
  await expect(page.getByTestId('shell-pulse')).toContainText('Dado')
  await expect(page.getByTestId('shell-pulse')).toContainText('Explorador')
  await expect(page.getByTestId('shell-pulse')).toContainText('Admin')
  await expect(page.getByTestId('library-grid')).toContainText('Outer Wilds')
  await expect(page.getByTestId('library-overview')).toContainText('Siguiente accion')
  await expect(page.getByTestId('library-overview')).toContainText('Inception')
  await expect(page.getByTestId('library-overview')).toContainText('Explorador')
  await expect(page.getByTestId('library-next-plan')).toContainText('Plan rapido')
  await expect(page.getByTestId('library-next-plan')).toContainText('Continuar sin perder contexto')
  await expect(page.getByTestId('library-next-plan')).toContainText('Importacion')
  await expect(page.getByRole('button', { name: 'Afinar ficha' })).toBeVisible()
  await expect(page.getByTestId('launch-guide')).toContainText('Plan de arranque')
  await expect(page.getByTestId('launch-guide')).toContainText('Base privada')
  await expect(page.getByTestId('launch-guide')).toContainText('Dado vivo')
  await expect(page.getByTestId('launch-guide')).toContainText('Explorador limpio')
  await expect(page.getByTestId('library-focus-shelf')).toContainText('En foco')
  await expect(page.getByTestId('library-focus-shelf')).toContainText('1984 - George Orwell')
  await expect(page.getByRole('button', { name: 'Todo 7' })).toBeVisible()
  await expect(page.getByTestId('library-smart-views')).toContainText('Listas para dado')
  await expect(page.getByTestId('library-smart-views')).toContainText('Sin contexto')
  await page.getByTestId('library-smart-views').getByRole('button', { name: /Sin contexto/ }).click()
  await expect(page.getByText('Vista: Sin contexto')).toBeVisible()
  await expect(page.getByText('4 de 7 entradas')).toBeVisible()
  await expect(page.getByTestId('library-grid')).toContainText('Inception')
  await expect(page.getByTestId('library-grid')).not.toContainText('Outer Wilds')
  await page.getByRole('button', { name: 'Restablecer vista' }).click()
  await expect(page.getByLabel('Ordenar biblioteca')).toHaveValue('focus')
  await page.getByLabel('Ordenar biblioteca').selectOption('title')
  await expect(page.getByText('Orden: Titulo')).toBeVisible()
  await expect(page.locator('[data-testid="library-grid"] .item-card').first()).toContainText('1984 - George Orwell')
  await page.getByRole('button', { name: 'Restablecer vista' }).click()
  await expect(page.getByLabel('Ordenar biblioteca')).toHaveValue('focus')
  await page.getByRole('button', { name: 'Lista', exact: true }).click()
  await expect(page.getByTestId('library-grid')).toHaveClass(/list-view/)
  await page.getByRole('button', { name: 'Dado', exact: true }).click()
  await page.getByRole('button', { name: 'Biblioteca', exact: true }).click()
  await expect(page.getByTestId('library-grid')).toHaveClass(/list-view/)
  await page.getByRole('button', { name: 'Tarjetas' }).click()
  await expect(page.getByTestId('library-grid')).not.toHaveClass(/list-view/)
  await page.getByLabel('Buscar en biblioteca').fill('zzzz no match')
  await expect(page.getByRole('heading', { name: 'Sin resultados' })).toBeVisible()
  await expect(page.getByText('0 de 7 entradas')).toBeVisible()
  await expect(page.getByTestId('library-focus-shelf')).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'Crear entrada zzzz no match' })).toBeVisible()
  await page.getByRole('button', { name: 'Quitar filtros' }).click()
  await expect(page.getByTestId('library-focus-shelf')).toBeVisible()
  await expect(page.getByTestId('library-grid')).toContainText('Outer Wilds')
  const outerWildsCard = page.locator('.item-card').filter({ hasText: 'Outer Wilds' })
  await expect(outerWildsCard.getByLabel('Pulso de Outer Wilds')).toContainText('Dado')
  await expect(outerWildsCard.getByLabel('Pulso de Outer Wilds')).toContainText('Foco')
  await expect(outerWildsCard.getByLabel('Pulso de Outer Wilds')).toContainText('Sorpresa')
  await expect(outerWildsCard.getByLabel('Senales rapidas de Outer Wilds')).toContainText('Importacion')
  await expect(outerWildsCard.getByLabel('Senales rapidas de Outer Wilds')).toContainText('12-20h')
  await page.getByRole('button', { name: 'Anadir' }).click()
  const quickEditor = page.getByRole('dialog', { name: 'Entrada' })
  await expect(quickEditor.getByTestId('personal-readiness')).toContainText('Preparacion')
  await expect(quickEditor.getByTestId('personal-readiness')).toContainText('Ficha por afinar')
  await quickEditor.getByLabel('Titulo').fill('Manual de prueba')
  await expect(quickEditor.getByLabel('Inicio rapido de entrada')).toContainText('Parte de una receta')
  await quickEditor.getByLabel('Medio de inicio rapido').selectOption('book')
  await expect(quickEditor.getByLabel('Tipo')).toHaveValue('book')
  await quickEditor.getByRole('button', { name: 'Aplicar plantilla Ideas grandes para Libros' }).click()
  await expect(quickEditor.getByLabel('Generos', { exact: true })).toHaveValue('Ciencia ficcion, Distopia, Filosofia')
  await expect(quickEditor.getByLabel('Tags', { exact: true })).toHaveValue('introspectivo, politico, premiado')
  await expect(quickEditor.getByLabel('Mood tags')).toHaveValue('denso, raro')
  await quickEditor.getByLabel('Notas').fill('Entrada manual con contexto inicial.')
  await expect(quickEditor.getByTestId('personal-readiness')).toContainText('Ficha lista')
  await quickEditor.getByRole('button', { name: 'Guardar' }).click()
  await expect(page.getByText('Manual de prueba guardada en Biblioteca')).toBeVisible()
  await expect(page.getByTestId('session-activity')).toContainText('Ficha guardada')
  await expect(page.getByTestId('session-activity')).toContainText('Manual de prueba')
  await page.getByTestId('session-activity').getByRole('button', { name: 'Limpiar' }).click()
  await expect(page.getByTestId('session-activity')).not.toBeVisible()
  await expect(page.getByTestId('library-grid')).toContainText('Manual de prueba')
  await page.locator('.item-main').filter({ hasText: 'Outer Wilds' }).click()
  await expect(page.getByRole('dialog', { name: 'Entrada' })).toBeVisible()
  await expect(page.getByTestId('personal-readiness')).toContainText('Preparacion')
  await expect(page.getByLabel('Prioridad')).toBeVisible()
  await expect(page.getByLabel('Sorpresa')).toBeVisible()
  await page.getByRole('textbox', { name: 'Progreso' }).fill('Cambio temporal sin guardar.')
  await page.getByRole('button', { name: 'Cerrar', exact: true }).click()
  await expect(page.getByLabel('Cambios sin guardar')).toContainText('Guarda la ficha')
  await page.getByRole('button', { name: 'Seguir editando' }).click()
  await expect(page.getByRole('textbox', { name: 'Progreso' })).toHaveValue('Cambio temporal sin guardar.')
  await page.getByRole('button', { name: 'Cerrar', exact: true }).click()
  await page.getByRole('button', { name: 'Descartar cambios' }).click()
  await expect(page.getByRole('button', { name: 'Empezar Outer Wilds' })).toBeVisible()
  await page.getByRole('button', { name: 'Mas acciones Outer Wilds' }).click()
  await expect(page.getByRole('menu', { name: 'Acciones Outer Wilds' })).toBeVisible()
  await expect(page.getByRole('menuitem', { name: 'Completar Outer Wilds' })).toBeVisible()
  await expect(page.getByRole('menuitem', { name: 'Copiar enlace Outer Wilds' })).toBeVisible()
  await page.getByRole('menuitem', { name: 'Copiar enlace Outer Wilds' }).click()
  await expect(page.getByText(/Enlace de Outer Wilds/)).toBeVisible()
  await page.getByRole('button', { name: 'Mas acciones Outer Wilds' }).click()
  await page.getByRole('menuitem', { name: 'Borrar Outer Wilds' }).click()
  await expect(page.getByRole('dialog', { name: 'Borrar entrada' })).toContainText('Outer Wilds')
  await page.getByRole('button', { name: 'Cancelar' }).click()
  await page.getByRole('button', { name: 'Empezar Outer Wilds' }).click()
  await expect(page.getByText('Outer Wilds ahora es En progreso')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Completar Outer Wilds' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Deshacer estado' })).toBeVisible()
  await page.getByRole('button', { name: 'Deshacer estado' }).click()
  await expect(page.getByText('Outer Wilds recuperado como Pendiente')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Empezar Outer Wilds' })).toBeVisible()
  await page.getByRole('button', { name: 'Empezar Outer Wilds' }).click()
  await expect(page.getByText('Outer Wilds ahora es En progreso')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Completar Outer Wilds' })).toBeVisible()

  await page.getByRole('button', { name: 'Dado', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Elige el siguiente hilo' })).toBeVisible()
  await expect(page.getByTestId('dice-readiness')).toContainText('Listo para tirar')
  await expect(page.getByTestId('dice-readiness')).toContainText('Candidatas')
  await expect(page.getByTestId('dice-readiness')).toContainText('Ajustes')
  await expect(page.getByRole('heading', { name: 'En la mesa' })).toBeVisible()
  await expect(page.getByTestId('dice-candidate-list')).toContainText('#1')
  await expect(page.getByTestId('dice-candidate-list')).toContainText('Score')
  await expect(page.getByRole('button', { name: 'Ver 1 mas' })).toBeVisible()
  await page.getByRole('button', { name: 'Ver 1 mas' }).click()
  await expect(page.getByRole('button', { name: 'Ver menos candidatas' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Elegibilidad' })).toBeVisible()
  await expect(page.getByText(/pueden salir ahora/)).toBeVisible()
  await expect(page.getByText('Pausados fuera')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Ajustes guardados' })).toBeDisabled()
  await page.getByLabel('Medio').selectOption('manhwa')
  await expect(page.getByTestId('dice-readiness')).toContainText('Sin tirada posible')
  await expect(page.getByTestId('dice-recovery')).toContainText('Abrir abanico')
  await expect(page.getByTestId('dice-recovery')).toContainText('Quitar tiempo')
  await expect(page.getByTestId('dice-recovery')).toContainText('Sorpresa amplia')
  await page.getByTestId('dice-recovery').getByRole('button', { name: /Abrir abanico/ }).click()
  await expect(page.getByLabel('Medio')).toHaveValue('any')
  await expect(page.getByLabel('Incluir pausados')).toBeChecked()
  await expect(page.getByTestId('dice-readiness')).toContainText('Listo para tirar')
  await page.getByRole('button', { name: 'Aplicar preset Noche ligera' }).click()
  await expect(page.getByLabel('Energia')).toHaveValue('low')
  await expect(page.getByLabel('Porcentaje de sorpresa')).toHaveValue('15')
  await expect(page.getByTestId('dice-readiness')).toContainText('!')
  await expect(page.getByText('Cambios pendientes')).toBeVisible()
  await page.getByLabel('Energia').selectOption('high')
  await page.getByLabel('Incluir pausados').check()
  await expect(page.getByText('Incluye pausados')).toBeVisible()
  await expect(page.getByText('Cambios pendientes')).toBeVisible()
  await page.getByRole('button', { name: 'Biblioteca', exact: true }).click()
  await expect(page.getByLabel('Salida con cambios pendientes')).toContainText('Cambios pendientes en Dado')
  await page.getByLabel('Salida con cambios pendientes').getByRole('button', { name: 'Seguir editando' }).click()
  await expect(page.getByRole('heading', { name: 'Elige el siguiente hilo' })).toBeVisible()
  await expect(page.getByText('Cambios pendientes')).toBeVisible()
  await page.getByRole('button', { name: 'Guardar ajustes' }).click()
  await expect(page.getByText('Ajustes del dado guardados')).toBeVisible()
  await expect(page.getByTestId('session-activity')).toContainText('Preferencias guardadas')
  await expect(page.getByRole('button', { name: 'Deshacer ajustes del dado' })).toBeVisible()
  await page.getByRole('button', { name: 'Deshacer ajustes del dado' }).click()
  await expect(page.getByText('Ajustes del dado recuperados')).toBeVisible()
  await expect(page.getByTestId('session-activity')).toContainText('Preferencias recuperadas')
  await expect(page.getByLabel('Energia')).toHaveValue('medium')
  await expect(page.getByLabel('Porcentaje de sorpresa')).toHaveValue('30')
  await expect(page.getByLabel('Incluir pausados')).not.toBeChecked()
  await expect(page.getByRole('button', { name: 'Ajustes guardados' })).toBeDisabled()
  await page.getByTestId('roll-button').click()
  await expect(page.getByTestId('recommendation-result')).toBeVisible()
  await expect(page.getByTestId('recommendation-result')).toContainText('Score')
  await expect(page.getByTestId('recommendation-result')).toContainText('Plan de sesion')
  await expect(page.getByTestId('recommendation-result')).toContainText('Decision')
  await expect(page.getByTestId('recommendation-result')).toContainText('Por que sale')
  await expect(page.getByTestId('dice-learning')).toContainText('Aprendizaje')
  await expect(page.getByTestId('dice-learning')).toContainText('Aprender gustos')
  await page.getByRole('button', { name: 'Aprender gustos' }).click()
  await expect(page.getByText(/gustos aprendidos/)).toBeVisible()
  await expect(page.getByTestId('session-activity')).toContainText('Gustos aprendidos')
  await expect(page.getByRole('button', { name: 'Deshacer gustos' })).toBeVisible()
  await page.getByRole('button', { name: 'Deshacer gustos' }).click()
  await expect(page.getByText('Gustos del dado recuperados')).toBeVisible()
  await page.getByRole('button', { name: 'Afinar ficha recomendada' }).click()
  const diceEditor = page.getByRole('dialog', { name: 'Entrada' })
  await expect(diceEditor.getByTestId('personal-readiness')).toContainText('Preparacion')
  await diceEditor.getByLabel('Notas').fill('Afinada desde el dado.')
  await diceEditor.getByRole('button', { name: 'Guardar' }).click()
  await expect(page.getByText(/afinada desde el dado\./)).toBeVisible()
  await expect(page.getByTestId('recent-rolls')).toContainText('Ahora mismo')
  await page.getByTestId('recent-rolls').getByRole('button', { name: /Afinar tirada reciente/ }).click()
  const recentEditor = page.getByRole('dialog', { name: 'Entrada' })
  await expect(recentEditor.getByLabel('Notas')).toHaveValue('Afinada desde el dado.')
  await recentEditor.getByRole('textbox', { name: 'Progreso' }).fill('Revisada desde historial.')
  await recentEditor.getByRole('button', { name: 'Guardar' }).click()
  await expect(page.getByText(/afinada desde el dado\./)).toBeVisible()
  await page.getByRole('button', { name: 'No hoy' }).click()
  await expect(page.getByText(/queda fuera hasta manana/)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Deshacer enfriado' })).toBeVisible()
  await page.getByRole('button', { name: 'Deshacer enfriado' }).click()
  await expect(page.getByText(/reactivado para el dado/)).toBeVisible()
  await expect(page.getByTestId('recommendation-result')).toContainText('Decision')
  await page.getByRole('button', { name: 'Empezar' }).click()
  await expect(page.getByText(/marcado como en progreso/)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Deshacer estado' })).toBeVisible()
  await page.getByRole('button', { name: 'Deshacer estado' }).click()
  await expect(page.getByText(/recuperado como/)).toBeVisible()

  await page.getByRole('button', { name: 'Biblioteca', exact: true }).click()
  await page.getByRole('button', { name: 'Mas acciones Outer Wilds' }).click()
  await expect(page.getByRole('menuitem', { name: 'Enfriar dado Outer Wilds' })).toBeVisible()
  await page.getByRole('menuitem', { name: 'Enfriar dado Outer Wilds' }).click()
  await expect(page.getByText('Outer Wilds enfriado para el dado')).toBeVisible()
  await expect(outerWildsCard.getByLabel('Pulso de Outer Wilds')).toContainText('Cooldown')
  await page.getByRole('button', { name: 'Mas acciones Outer Wilds' }).click()
  await expect(page.getByRole('menuitem', { name: 'Reactivar dado Outer Wilds' })).toBeVisible()

  await page.getByRole('button', { name: 'Dado', exact: true }).click()
  await page.getByLabel('Medio').selectOption('game')
  await page.getByLabel('Incluir pausados').uncheck()
  await expect(page.getByTestId('dice-readiness')).toContainText('Sin tirada posible')
  await expect(page.getByTestId('dice-recovery')).toContainText('Reactivar cooldowns')
  await page.getByTestId('dice-recovery').getByRole('button', { name: /Reactivar cooldowns/ }).click()
  await expect(page.getByText('1 entrada reactivada para el dado')).toBeVisible()
  await expect(page.getByTestId('dice-readiness')).toContainText('Listo para tirar')
  await expect(page.getByRole('button', { name: 'Deshacer reactivacion' })).toBeVisible()
  await page.getByRole('button', { name: 'Deshacer reactivacion' }).click()
  await expect(page.getByText('1 cooldown recuperado')).toBeVisible()
  await expect(page.getByTestId('dice-readiness')).toContainText('Sin tirada posible')
  await page.getByTestId('dice-recovery').getByRole('button', { name: /Reactivar cooldowns/ }).click()
  await expect(page.getByText('1 entrada reactivada para el dado')).toBeVisible()
  await expect(page.getByTestId('dice-readiness')).toContainText('Listo para tirar')

  await page.getByRole('button', { name: 'Biblioteca', exact: true }).click()
  await expect(page.getByLabel('Salida con cambios pendientes')).toContainText('Cambios pendientes en Dado')
  await page.getByLabel('Salida con cambios pendientes').getByRole('button', { name: 'Descartar cambios' }).click()
  await expect(outerWildsCard.getByLabel('Pulso de Outer Wilds')).toContainText('Continuar')
})

test('mobile layout keeps the core controls reachable', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByTestId('library-overview')).toBeVisible()
  await expect(page.getByLabel('Buscar en biblioteca')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Explorador', exact: true })).toBeVisible()
  await page.getByRole('button', { name: 'Dado', exact: true }).click()
  await expect(page.getByRole('button', { name: 'Tirar dado ponderado' })).toBeVisible()
})

test('library empty search can create a prefilled item', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Buscar en biblioteca').fill('Manual sombra')
  await expect(page.getByRole('heading', { name: 'Sin resultados' })).toBeVisible()
  await page.getByRole('button', { name: 'Crear entrada Manual sombra' }).click()

  const searchDraftEditor = page.getByRole('dialog', { name: 'Entrada' })
  await expect(searchDraftEditor.getByLabel('Titulo')).toHaveValue('Manual sombra')
  await searchDraftEditor.getByLabel('Notas').fill('Creada desde una busqueda vacia.')
  await searchDraftEditor.getByRole('button', { name: 'Guardar' }).click()

  await expect(page.getByText('Manual sombra guardada en Biblioteca')).toBeVisible()
  await expect(page.getByTestId('library-grid')).toContainText('Manual sombra')
})

test('library can update selected visible items in bulk', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Seleccionar visibles' }).click()
  await expect(page.getByLabel('Seleccion de biblioteca')).toContainText('7 seleccionadas')
  await page.getByRole('button', { name: 'Quitar visibles' }).click()
  await expect(page.getByLabel('Seleccion de biblioteca')).not.toContainText('seleccionadas')

  await page.getByLabel('Seleccionar Outer Wilds').check()
  await page.getByLabel('Seleccionar Vinland Saga').check()

  const selectionBar = page.getByLabel('Seleccion de biblioteca')
  await expect(selectionBar).toContainText('2 seleccionadas')
  await selectionBar.getByLabel('Estado para seleccion').selectOption('completed')
  await selectionBar.getByRole('button', { name: 'Aplicar estado' }).click()

  await expect(page.getByText('2 entradas ahora son Completado')).toBeVisible()
  await expect(page.locator('.item-card', { hasText: 'Outer Wilds' })).toContainText('Completado')
  await expect(page.locator('.item-card', { hasText: 'Vinland Saga' })).toContainText('Completado')

  await page.getByLabel('Accion reciente de biblioteca').getByRole('button', { name: 'Deshacer estado' }).click()
  await expect(page.getByText('2 estados recuperados')).toBeVisible()
  await expect(page.locator('.item-card', { hasText: 'Outer Wilds' })).toContainText('Pendiente')
  await expect(page.locator('.item-card', { hasText: 'Vinland Saga' })).toContainText('Pendiente')
})

test('quick search opens library items through the pending-change guard', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Dado', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Elige el siguiente hilo' })).toBeVisible()
  await page.getByLabel('Energia').selectOption('high')
  await expect(page.getByText('Cambios pendientes')).toBeVisible()

  await page.getByRole('button', { name: 'Busqueda rapida' }).click()
  const quickSearch = page.getByRole('dialog', { name: 'Abrir en Nexo' })
  await expect(quickSearch).toBeVisible()
  await quickSearch.getByLabel('Buscar en Nexo').fill('outer')
  await quickSearch.getByRole('button', { name: 'Abrir Outer Wilds' }).click()

  await expect(page.getByLabel('Salida con cambios pendientes')).toContainText('Cambios pendientes en Dado')
  await expect(page).toHaveURL(/tab=dice/)
  await page.getByLabel('Salida con cambios pendientes').getByRole('button', { name: 'Descartar cambios' }).click()
  await expect(page).toHaveURL(/item=game-outer-wilds/)
  await expect(page.getByRole('dialog', { name: 'Entrada' }).getByLabel('Titulo')).toHaveValue('Outer Wilds')
})

test('quick search opens the active result from the keyboard', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByRole('heading', { name: 'Biblioteca privada' })).toBeVisible()
  await page.keyboard.press('/')
  const quickSearch = page.getByRole('dialog', { name: 'Abrir en Nexo' })
  await expect(quickSearch).toBeVisible()
  const searchInput = quickSearch.getByLabel('Buscar en Nexo')
  await searchInput.fill('outer')
  await expect(quickSearch.getByRole('button', { name: 'Abrir Outer Wilds' })).toHaveAttribute('aria-current', 'true')
  await searchInput.press('Enter')
  await expect(page).toHaveURL(/item=game-outer-wilds/)
  await expect(page.getByRole('dialog', { name: 'Entrada' }).getByLabel('Titulo')).toHaveValue('Outer Wilds')
})

test('quick search opens sections through the pending-change guard', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Dado', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Elige el siguiente hilo' })).toBeVisible()
  await page.getByLabel('Energia').selectOption('high')
  await expect(page.getByText('Cambios pendientes')).toBeVisible()

  await page.getByRole('button', { name: 'Busqueda rapida' }).click()
  const quickSearch = page.getByRole('dialog', { name: 'Abrir en Nexo' })
  await quickSearch.getByLabel('Buscar en Nexo').fill('explorador')
  await expect(quickSearch.getByRole('button', { name: 'Abrir Explorador' })).toHaveAttribute('aria-current', 'true')
  await quickSearch.getByRole('button', { name: 'Abrir Explorador' }).click()

  await expect(page.getByLabel('Salida con cambios pendientes')).toContainText('Cambios pendientes en Dado')
  await expect(page).toHaveURL(/tab=dice/)
  await page.getByLabel('Salida con cambios pendientes').getByRole('button', { name: 'Descartar cambios' }).click()
  await expect(page).toHaveURL(/tab=explorer/)
  await expect(page.getByRole('heading', { name: 'Encuentra la proxima entrada' })).toBeVisible()
})

test('quick search can create a prefilled item through the pending-change guard', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Dado', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Elige el siguiente hilo' })).toBeVisible()
  await page.getByLabel('Energia').selectOption('high')
  await expect(page.getByText('Cambios pendientes')).toBeVisible()

  await page.getByRole('button', { name: 'Busqueda rapida' }).click()
  const quickSearch = page.getByRole('dialog', { name: 'Abrir en Nexo' })
  await quickSearch.getByLabel('Buscar en Nexo').fill('Manual global')
  await expect(quickSearch.getByRole('button', { name: 'Crear entrada Manual global' })).toHaveAttribute('aria-current', 'true')
  await quickSearch.getByRole('button', { name: 'Crear entrada Manual global' }).click()

  await expect(page.getByLabel('Salida con cambios pendientes')).toContainText('Cambios pendientes en Dado')
  await expect(page).toHaveURL(/tab=dice/)
  await page.getByLabel('Salida con cambios pendientes').getByRole('button', { name: 'Descartar cambios' }).click()

  const createdEditor = page.getByRole('dialog', { name: 'Entrada' })
  await expect(createdEditor.getByLabel('Titulo')).toHaveValue('Manual global')
  await createdEditor.getByLabel('Notas').fill('Creada desde busqueda rapida global.')
  await createdEditor.getByRole('button', { name: 'Guardar' }).click()
  await expect(page.getByText('Manual global guardada en Biblioteca')).toBeVisible()
})

test('activity entries navigate through the pending-change guard', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Anadir' }).click()
  const editor = page.getByRole('dialog', { name: 'Entrada' })
  await editor.getByLabel('Titulo').fill('Actividad navegable')
  await editor.getByRole('button', { name: 'Guardar' }).click()
  await expect(page.getByTestId('session-activity')).toContainText('Ficha guardada')

  await page.getByRole('button', { name: 'Dado', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Elige el siguiente hilo' })).toBeVisible()
  await page.getByLabel('Energia').selectOption('high')
  await expect(page.getByText('Cambios pendientes')).toBeVisible()

  await page
    .getByTestId('session-activity')
    .getByRole('button', { name: 'Abrir Ficha guardada en Biblioteca' })
    .click()
  await expect(page.getByLabel('Salida con cambios pendientes')).toContainText('Cambios pendientes en Dado')
  await expect(page.getByRole('heading', { name: 'Elige el siguiente hilo' })).toBeVisible()

  await page.getByLabel('Salida con cambios pendientes').getByRole('button', { name: 'Descartar cambios' }).click()
  await expect(page.getByRole('heading', { name: 'Biblioteca privada' })).toBeVisible()
  await expect(page).toHaveURL(/item=movie-actividad-navegable/)
  const focusedEditor = page.getByRole('dialog', { name: 'Entrada' })
  await expect(focusedEditor.getByLabel('Titulo')).toHaveValue('Actividad navegable')
})

test('library item deep links open and close the focused editor', async ({ page }) => {
  await page.goto('/?item=game-outer-wilds')
  const editor = page.getByRole('dialog', { name: 'Entrada' })
  await expect(editor.getByLabel('Titulo')).toHaveValue('Outer Wilds')
  await expect(page).toHaveURL(/item=game-outer-wilds/)
  await editor.getByRole('button', { name: 'Copiar enlace a Outer Wilds' }).click()
  await expect(editor.getByLabel('Enlace de ficha')).toHaveValue(/item=game-outer-wilds/)

  await editor.getByRole('button', { name: 'Cerrar', exact: true }).click()
  await expect(page.getByRole('dialog', { name: 'Entrada' })).not.toBeVisible()
  await expect(page).not.toHaveURL(/item=game-outer-wilds/)

  await page.goBack()
  await expect(page.getByRole('dialog', { name: 'Entrada' }).getByLabel('Titulo')).toHaveValue('Outer Wilds')
})

test('missing item deep links can recover through library search', async ({ page }) => {
  await page.goto('/?item=outer-wilds')
  await expect(page.getByLabel('Actividad sin entrada')).toContainText('outer wilds')
  await page.getByRole('button', { name: 'Buscar parecido' }).click()
  await expect(page).not.toHaveURL(/item=outer-wilds/)
  await expect(page.getByLabel('Buscar en biblioteca')).toHaveValue('outer wilds')
  await expect(page.getByTestId('library-grid')).toContainText('Outer Wilds')
})

test('dice item activity opens the linked library editor', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Dado', exact: true }).click()
  await page.getByTestId('roll-button').click()
  await expect(page.getByTestId('recommendation-result')).toBeVisible()
  await page.getByRole('button', { name: 'Afinar ficha recomendada' }).click()

  const diceEditor = page.getByRole('dialog', { name: 'Entrada' })
  const recommendedTitle = await diceEditor.getByLabel('Titulo').inputValue()
  await diceEditor.getByRole('textbox', { name: 'Progreso' }).fill('Vuelta desde actividad del dado.')
  await diceEditor.getByRole('button', { name: 'Guardar' }).click()
  await expect(page.getByTestId('session-activity')).toContainText('Ficha afinada')

  await page
    .getByTestId('session-activity')
    .getByRole('button', { name: 'Abrir Ficha afinada en Biblioteca' })
    .click()
  await expect(page).toHaveURL(/item=/)
  await expect(page.getByRole('dialog', { name: 'Entrada' }).getByLabel('Titulo')).toHaveValue(recommendedTitle)
})

test('pwa metadata is present', async ({ page }) => {
  await page.goto('/')

  await expect(page.locator('link[rel="manifest"]')).toHaveAttribute('href', '/manifest.webmanifest')
  await expect(page.locator('meta[name="theme-color"]')).toHaveAttribute('content', '#0f1214')

  const response = await page.request.get('/manifest.webmanifest')
  expect(response.ok()).toBe(true)
  const manifest = await response.json()
  expect(manifest).toEqual(expect.objectContaining({ display: 'standalone', id: '/', name: 'Nexo' }))
  expect(manifest.icons).toEqual(
    expect.arrayContaining([expect.objectContaining({ src: '/icons/nexo.svg', purpose: 'any maskable' })]),
  )
  expect(manifest.shortcuts).toEqual(
    expect.arrayContaining([
      expect.objectContaining({ name: 'Dado ponderado', url: '/?tab=dice' }),
      expect.objectContaining({ name: 'Explorador', url: '/?tab=explorer' }),
    ]),
  )

  await page.goto('/?tab=dice')
  await expect(page.getByRole('heading', { name: 'Elige el siguiente hilo' })).toBeVisible()
  await page.getByRole('button', { name: 'Explorador', exact: true }).click()
  await expect(page).toHaveURL(/tab=explorer/)
  await page.goBack()
  await expect(page).toHaveURL(/tab=dice/)
  await expect(page.getByRole('heading', { name: 'Elige el siguiente hilo' })).toBeVisible()
})

test('browser history asks before leaving pending dice preferences', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Dado', exact: true }).click()
  await expect(page).toHaveURL(/tab=dice/)
  await page.getByRole('button', { name: 'Explorador', exact: true }).click()
  await expect(page).toHaveURL(/tab=explorer/)
  await page.goBack()
  await expect(page).toHaveURL(/tab=dice/)
  await page.getByLabel('Energia').selectOption('high')
  await expect(page.getByText('Cambios pendientes')).toBeVisible()
  await page.goBack()
  await expect(page.getByLabel('Salida con cambios pendientes')).toContainText('Cambios pendientes en Dado')
  await expect(page).toHaveURL(/tab=dice/)
  await page.getByLabel('Salida con cambios pendientes').getByRole('button', { name: 'Descartar cambios' }).click()
  await expect(page.getByRole('heading', { name: 'Biblioteca privada' })).toBeVisible()
  await expect(page).not.toHaveURL(/tab=dice/)
})

test('settings show pending changes before saving preferences', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Ajustes', exact: true }).click()

  await expect(page.getByRole('button', { name: 'Guardado', exact: true })).toBeDisabled()
  await expect(page.getByRole('heading', { name: 'Roles' })).toBeVisible()
  await expect(page.getByLabel('Resumen de roles')).toContainText('Admin')
  await expect(page.getByLabel('Permisos de roles')).toContainText('Cambiar roles')
  await expect(page.getByLabel('Permisos de roles')).toContainText('Curar catalogo')
  await expect(page.getByTestId('settings-confidence')).toContainText('Cuenta lista')
  await expect(page.getByTestId('settings-confidence')).toContainText('Admin')
  await expect(page.getByTestId('settings-confidence')).toContainText('Entradas')
  await expect(page.getByRole('heading', { name: 'Datos privados' })).toBeVisible()
  await expect(page.getByLabel('Estado de datos privados')).toContainText('7')
  await expect(page.getByTestId('private-data-health')).toContainText('Salud de datos')
  await expect(page.getByTestId('private-data-health')).toContainText('Taxonomia')
  await expect(page.getByTestId('private-data-health')).toContainText('Catalogo Nexo')
  await expect(page.getByTestId('private-data-health')).toContainText('Dado')
  await expect(page.getByTestId('private-action-plan')).toContainText('Plan de mantenimiento')
  await expect(page.getByTestId('private-action-plan')).toContainText('Tirar dado')
  await expect(page.getByTestId('private-action-plan')).toContainText('Explorar catalogo')
  await expect(page.getByTestId('private-action-plan')).toContainText('Backup JSON')
  await expect(page.getByTestId('taste-suggestions')).toContainText('Sugerencias de gusto')
  await expect(page.getByTestId('taste-suggestions')).toContainText('sci-fi')
  await page.getByRole('button', { name: 'Aplicar sugerencias' }).click()
  await expect(page.getByLabel('Generos favoritos')).toHaveValue('sci-fi')
  await expect(page.getByLabel('Tags favoritos')).toHaveValue('pelicula, sci-fi')
  await expect(page.getByText('Cambios pendientes')).toBeVisible()
  await page.getByRole('button', { name: 'Guardar cambios' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Ajustes guardados' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Guardado', exact: true })).toBeDisabled()
  await page.getByTestId('private-action-plan').getByRole('button', { name: /Tirar dado/ }).click()
  await expect(page).toHaveURL(/tab=dice/)
  await page.getByRole('button', { name: 'Ajustes', exact: true }).click()
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Exportar backup JSON' }).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toMatch(/^nexo-backup-\d{4}-\d{2}-\d{2}\.json$/)
  await expect(page.getByText('Backup JSON descargado')).toBeVisible()
  await page.getByLabel('Importar backup JSON').setInputFiles({
    name: 'nexo-backup-import.json',
    mimeType: 'application/json',
    buffer: Buffer.from(
      JSON.stringify({
        schemaVersion: 1,
        exportedAt: '2026-06-03T00:00:00.000Z',
        items: [
          {
            title: 'Backup Probe',
            type: 'book',
            status: 'wishlist',
            genres: ['Ensayo'],
            tags: ['backup'],
            moodTags: [],
            weights: { priority: 1, surprise: 0.5, challenge: 0.5 },
            source: 'manual',
            createdAt: '2026-06-01T00:00:00.000Z',
            updatedAt: '2026-06-01T00:00:00.000Z',
          },
        ],
      }),
    ),
  })
  await expect(page.getByText('Backup preparado: 1 nueva / 0 actualizadas')).toBeVisible()
  await expect(page.getByLabel('Backup preparado')).toContainText('nexo-backup-import.json')
  await expect(page.getByLabel('Backup preparado')).toContainText('1 entradas revisadas antes de aplicar')
  await expect(page.getByText('Backup Probe')).not.toBeVisible()
  await page.getByRole('button', { name: 'Aplicar backup' }).click()
  await expect(page.getByText('Importadas 1 entradas desde backup')).toBeVisible()
  await expect(page.getByTestId('session-activity')).toContainText('Backup privado aplicado')
  await page.getByRole('button', { name: 'Biblioteca', exact: true }).click()
  await expect(page.getByTestId('library-grid')).toContainText('Backup Probe')
  await page.getByRole('button', { name: 'Ajustes', exact: true }).click()
  await expect(page.getByLabel('Rol de Usuario demo')).toHaveValue('user')
  await page.getByLabel('Rol de Usuario demo').selectOption('admin')
  await expect(page.getByLabel('Cambio de rol preparado')).toContainText('Usuario demo')
  await expect(page.getByLabel('Cambio de rol preparado')).toContainText('Usuario -> Admin')
  await page.getByRole('button', { name: 'Cancelar' }).click()
  await expect(page.getByText('Cambio de rol cancelado')).toBeVisible()
  await expect(page.getByLabel('Rol de Usuario demo')).toHaveValue('user')
  await page.getByLabel('Rol de Usuario demo').selectOption('moderator')
  await expect(page.getByLabel('Cambio de rol preparado')).toContainText('Usuario -> Moderador')
  await page.getByRole('button', { name: 'Aplicar rol' }).click()
  await expect(page.getByText('Usuario demo ahora es Moderador')).toBeVisible()
  await expect(page.getByTestId('session-activity')).toContainText('Rol actualizado')
  await page.getByRole('button', { name: 'Claro', exact: true }).click()
  await expect(page.getByTestId('settings-confidence')).toContainText('Ajustes pendientes')
  await expect(page.getByText('Cambios pendientes')).toBeVisible()
  await page.getByRole('button', { name: 'Biblioteca', exact: true }).click()
  await expect(page.getByLabel('Salida con cambios pendientes')).toContainText('Cambios pendientes en Ajustes')
  await page.getByLabel('Salida con cambios pendientes').getByRole('button', { name: 'Seguir editando' }).click()
  await expect(page.getByTestId('settings-confidence')).toContainText('Ajustes pendientes')
  await page.getByRole('button', { name: 'Biblioteca', exact: true }).click()
  await page.getByLabel('Salida con cambios pendientes').getByRole('button', { name: 'Descartar cambios' }).click()
  await expect(page.getByRole('heading', { name: 'Biblioteca privada' })).toBeVisible()
  await page.getByRole('button', { name: 'Ajustes', exact: true }).click()
  await expect(page.getByTestId('settings-confidence')).toContainText('Oscuro')
  await page.getByRole('button', { name: 'Claro', exact: true }).click()
  await expect(page.getByTestId('settings-confidence')).toContainText('Ajustes pendientes')
  await page.getByRole('button', { name: 'Guardar cambios' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Ajustes guardados' })).toBeVisible()
  await expect(page.getByTestId('session-activity')).toContainText('Ajustes guardados')
  await expect(page.getByRole('button', { name: 'Deshacer ajustes' })).toBeVisible()
  await page.getByRole('button', { name: 'Deshacer ajustes' }).click()
  await expect(page.getByRole('status').filter({ hasText: 'Ajustes recuperados' })).toBeVisible()
  await expect(page.getByTestId('session-activity')).toContainText('Ajustes recuperados')
  await expect(page.getByTestId('settings-confidence')).toContainText('Oscuro')
  await expect(page.getByRole('button', { name: 'Guardado', exact: true })).toBeDisabled()
})

test('library quick import previews a backup before applying it', async ({ page }) => {
  await page.goto('/')
  await page.getByLabel('Importar biblioteca desde JSON').setInputFiles({
    name: 'nexo-library-preview.json',
    mimeType: 'application/json',
    buffer: Buffer.from(
      JSON.stringify({
        schemaVersion: 1,
        exportedAt: '2026-06-03T00:00:00.000Z',
        items: [
          {
            title: 'Preview Probe',
            type: 'movie',
            status: 'wishlist',
            genres: ['Drama'],
            tags: ['preview'],
            moodTags: [],
            weights: { priority: 1, surprise: 0.5, challenge: 0.5 },
            source: 'manual',
            createdAt: '2026-06-01T00:00:00.000Z',
            updatedAt: '2026-06-01T00:00:00.000Z',
          },
        ],
      }),
    ),
  })

  await expect(page.getByText('Backup preparado: 1 nueva / 0 actualizadas')).toBeVisible()
  await expect(page.getByLabel('Backup preparado en biblioteca')).toContainText('nexo-library-preview.json')
  await expect(page.getByText('Preview Probe')).not.toBeVisible()
  await page.getByRole('button', { name: 'Aplicar backup' }).click()
  await expect(page.getByText('Importadas 1 entradas')).toBeVisible()
  await expect(page.getByTestId('library-grid')).toContainText('Preview Probe')
})

test('explorer searches public catalog and saves to private library', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Explorador', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Encuentra la proxima entrada' })).toBeVisible()
  await expect(page.getByLabel('Resumen del explorador')).toContainText('Cola')
  await page.getByLabel('Tipo de busqueda en explorador').selectOption('game')
  await page.getByRole('button', { name: 'Ajustes' }).click()
  await expect(page.getByLabel('Tipo por defecto')).toHaveValue('game')
  await page.getByRole('button', { name: 'Explorador', exact: true }).click()
  await expect(page.getByLabel('Tipo de busqueda en explorador')).toHaveValue('game')
  await page.getByLabel('Buscar en explorador').fill('Odisea')
  await page.getByRole('button', { name: 'Buscar' }).click()
  await expect(page.getByTestId('session-activity')).toContainText('Busqueda en cola')

  await expect(page.getByTestId('explorer-decision-panel')).toContainText('Bandeja activa')
  await expect(page.getByTestId('explorer-decision-panel')).toContainText('Odisea')
  await expect(page.getByRole('button', { name: /APIs/ })).toBeVisible()
  await page.getByRole('button', { name: /APIs/ }).click()
  await expect(page.getByTestId('explorer-decision-panel')).toContainText('APIs activo')
  await expect(page.getByText('Odisea').first()).toBeVisible()
  await page.getByRole('button', { name: /Nexo/ }).click()
  await expect(page.getByRole('heading', { name: 'Sin resultados Nexo' })).toBeVisible()
  await page.getByRole('button', { name: 'Ver todos los origenes' }).click()
  const odiseaSpotlight = page.getByTestId('candidate-spotlight')
  await expect(odiseaSpotlight).toContainText('Odisea')
  await expect(odiseaSpotlight).toContainText('Que hacer ahora')
  await expect(odiseaSpotlight).toContainText('Resultado externo')
  await expect(odiseaSpotlight).toContainText('Guardar o curar catalogo')
  await expect(odiseaSpotlight.getByLabel('Decidir Odisea')).toContainText('Guardar')
  await odiseaSpotlight.getByRole('button', { name: 'Descartar Odisea' }).click()
  await page.getByRole('tab', { name: /Descartados 1/ }).click()
  await expect(page.getByText('Apartado de tus pendientes')).toBeVisible()
  await page.getByRole('button', { name: 'Recuperar Odisea' }).click()
  await expect(page.getByRole('tab', { name: /En cola 1/ })).toBeVisible()
  await page.getByTestId('candidate-spotlight').getByRole('button', { name: 'Abrir ficha Odisea' }).click()
  await expect(page.getByRole('dialog', { name: 'Odisea' })).toContainText('En cola')
  await page.getByRole('button', { name: 'Guardar en Biblioteca' }).click()
  await expect(page.getByRole('dialog', { name: 'Odisea' })).not.toBeVisible()
  await expect(page.getByTestId('session-activity')).toContainText('Hallazgo guardado')
  await expect(page.getByRole('button', { name: 'Afinar ficha guardada Odisea' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Deshacer guardado' })).toBeVisible()
  await page.getByRole('button', { name: 'Deshacer guardado' }).click()
  await expect(page.getByText('Odisea recuperado a la cola y eliminado de Biblioteca.')).toBeVisible()
  await expect(page.getByTestId('session-activity')).toContainText('Guardado deshecho')
  await page.getByRole('button', { name: 'Biblioteca', exact: true }).click()
  await expect(page.getByTestId('library-grid')).not.toContainText('Odisea')
  await page.getByRole('button', { name: 'Explorador', exact: true }).click()
  await expect(page.getByRole('tab', { name: /En cola 1/ })).toBeVisible()
  await page.getByTestId('candidate-spotlight').getByRole('button', { name: 'Guardar Odisea' }).click()
  await expect(page.getByRole('button', { name: 'Afinar ficha guardada Odisea' })).toBeVisible()
  await page.getByRole('button', { name: 'Afinar ficha guardada Odisea' }).click()
  const savedEditor = page.getByRole('dialog', { name: 'Entrada' })
  await expect(savedEditor.getByLabel('Titulo')).toHaveValue('Odisea')
  await savedEditor.getByLabel('Notas').fill('Afinada desde Explorador.')
  await savedEditor.getByRole('button', { name: 'Guardar' }).click()
  await expect(page.getByText('Odisea afinada en Biblioteca.')).toBeVisible()
  await expect(page.getByTestId('session-activity')).toContainText('Ficha afinada')
  await page.getByRole('tab', { name: /Guardados 1/ }).click()
  await expect(page.getByText('Ya esta en tu biblioteca')).toBeVisible()
  await expect(page.getByText('Odisea').first()).toBeVisible()
  await page.getByLabel('Buscar en explorador').fill('Odisea')
  await page.getByRole('button', { name: 'Buscar' }).click()
  await expect(page.getByText('No hay hallazgos nuevos para esa busqueda.')).toBeVisible()
  await expect(page.getByRole('tab', { name: /En cola 0/ })).toBeVisible()
  await expect(page.getByRole('tab', { name: /Guardados 1/ })).toBeVisible()
  await page.getByRole('button', { name: 'Biblioteca', exact: true }).click()
  await expect(page.getByTestId('library-grid')).toContainText('Odisea')
  await page.locator('.item-main').filter({ hasText: 'Odisea' }).click()
  const editor = page.getByRole('dialog', { name: 'Entrada' })
  await expect(editor).toContainText('Origen')
  await expect(editor).toContainText('API externa')
  await expect(editor).toContainText('Esta ficha vive solo en tu biblioteca privada.')
})

test('explorer can clean a filtered queued view', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Explorador', exact: true }).click()
  await page.getByLabel('Tipo de busqueda en explorador').selectOption('book')
  await page.getByLabel('Buscar en explorador').fill('Odisea')
  await page.getByRole('button', { name: 'Buscar' }).click()

  await page.getByRole('button', { name: /APIs/ }).click()
  await expect(page.getByTestId('explorer-decision-panel')).toContainText('APIs activo')
  await expect(page.getByTestId('explorer-decision-panel')).toContainText('Descartar vista')
  await page.getByRole('button', { name: 'Descartar vista' }).click()

  await expect(page.getByText('Odisea descartado de la vista APIs.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Deshacer descarte' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Sin resultados APIs' })).toBeVisible()
  await page.getByRole('button', { name: 'Deshacer descarte' }).click()
  await expect(page.getByText('Odisea recuperado a la cola.')).toBeVisible()
  await expect(page.getByTestId('candidate-spotlight')).toContainText('Odisea')
  await page.getByRole('button', { name: 'Descartar vista' }).click()
  await expect(page.getByText('Odisea descartado de la vista APIs.')).toBeVisible()
  await page.getByRole('button', { name: 'Ver todos los origenes' }).click()
  await expect(page.getByTestId('candidate-spotlight')).toContainText('Nexo')
  await expect(page.getByTestId('candidate-spotlight')).toContainText('Odisea')
  await expect(page.getByTestId('candidate-spotlight')).toContainText('Ficha curada de Nexo')
  await expect(page.getByTestId('candidate-spotlight')).toContainText('Guardar copia privada')
})

test('explorer can save a filtered queued view in bulk and undo it', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Explorador', exact: true }).click()
  await page.getByLabel('Tipo de busqueda en explorador').selectOption('book')
  await page.getByLabel('Buscar en explorador').fill('Odisea')
  await page.getByRole('button', { name: 'Buscar' }).click()

  await page.getByRole('button', { name: /APIs/ }).click()
  await expect(page.getByTestId('explorer-decision-panel')).toContainText('APIs activo')
  await expect(page.getByTestId('explorer-decision-panel')).toContainText('Guardar vista')
  await page.getByRole('button', { name: 'Guardar vista' }).click()

  await expect(page.getByText('Odisea guardado desde la vista APIs.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Afinar ficha guardada Odisea' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Deshacer guardado de vista' })).toBeVisible()
  await expect(page.getByRole('tab', { name: /Guardados 1/ })).toBeVisible()

  await page.getByRole('button', { name: 'Deshacer guardado de vista' }).click()
  await expect(page.getByText('Odisea recuperado a la cola y eliminado de Biblioteca.')).toBeVisible()
  await expect(page.getByRole('tab', { name: /En cola 2/ })).toBeVisible()
  await page.getByRole('button', { name: 'Biblioteca', exact: true }).click()
  await expect(page.getByTestId('library-grid')).not.toContainText('Odisea')
})

test('library editor explains private copies from the Nexo catalog', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Explorador', exact: true }).click()
  await page.getByLabel('Tipo de busqueda en explorador').selectOption('book')
  await page.getByLabel('Buscar en explorador').fill('Odisea')
  await page.getByRole('button', { name: 'Buscar' }).click()

  const nexoSpotlight = page.getByTestId('candidate-spotlight')
  await expect(nexoSpotlight).toContainText('Nexo')
  await expect(nexoSpotlight).toContainText('Odisea')
  await nexoSpotlight.getByRole('button', { name: 'Guardar Odisea' }).click()

  await page.getByRole('button', { name: 'Biblioteca', exact: true }).click()
  await expect(page.getByTestId('library-grid')).toContainText('Odisea')
  await page.locator('.item-main').filter({ hasText: 'Odisea' }).click()

  const editor = page.getByRole('dialog', { name: 'Entrada' })
  await expect(editor).toContainText('Catalogo Nexo')
  await expect(editor).toContainText('Tus notas, rating, estado, progreso y pesos del dado no cambian el catalogo publico.')
  await expect(editor).toContainText('Referencias')
})

test('moderator curation can create a public catalog item in demo mode', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Curacion' }).click()
  await expect(page.getByRole('heading', { name: 'Curacion' })).toBeVisible()
  await expect(page.getByTestId('catalog-diagnostics')).toContainText('Diagnostico')
  await expect(page.getByTestId('catalog-diagnostics')).toContainText('Portada')
  await expect(page.getByTestId('catalog-diagnostics')).toContainText('Descripcion')
  await page.getByTestId('catalog-diagnostics').getByRole('button', { name: /Portada/ }).click()
  await expect(page.getByTestId('catalog-diagnostics')).toContainText('Viendo sin portada')
  await expect(page.getByRole('heading', { name: 'Arrival' })).toBeVisible()
  await page.getByRole('button', { name: 'Quitar foco' }).click()
  await expect(page.getByTestId('catalog-diagnostics')).not.toContainText('Viendo sin portada')
  await expect(page.getByRole('heading', { name: 'Revision prioritaria' })).toBeVisible()
  await expect(page.getByLabel('Revision prioritaria del catalogo')).toContainText('Sin portada')
  await page.getByRole('button', { name: 'Revisar Arrival' }).click()
  await expect(page.locator('.public-item-editor').getByLabel('Titulo')).toHaveValue('Arrival')
  await page.getByRole('button', { name: 'Cerrar', exact: true }).click()

  const templateLauncher = page.getByRole('region', { name: 'Plantillas de curacion' })
  await expect(templateLauncher).toContainText('Empieza con generos predefinidos')
  await page.getByLabel('Medio de plantillas de curacion').selectOption('game')
  await expect(templateLauncher).toContainText('Survival craft')
  await page.getByRole('button', { name: 'Usar plantilla Survival craft para Juegos' }).click()
  const templatedEditor = page.locator('.public-item-editor')
  await expect(templatedEditor.getByLabel('Tipo')).toHaveValue('game')
  await expect(templatedEditor.getByLabel('Generos', { exact: true })).toHaveValue('Supervivencia, Crafting, Accion')
  await expect(templatedEditor.getByLabel('Tags', { exact: true })).toHaveValue('cooperativo, base building, mundo abierto')
  await expect(templatedEditor.getByLabel('Mood tags')).toHaveValue('intenso')
  await templatedEditor.getByLabel('Titulo').fill('Borrador temporal')
  await page.getByRole('button', { name: 'Cerrar', exact: true }).click()
  await expect(page.getByLabel('Cambios sin guardar')).toContainText('Guarda la ficha')
  await page.getByRole('button', { name: 'Seguir editando' }).click()
  await expect(templatedEditor.getByLabel('Titulo')).toHaveValue('Borrador temporal')
  await expect(templatedEditor.getByLabel('Mood tags')).toHaveValue('intenso')
  await page.getByRole('button', { name: 'Cerrar', exact: true }).click()
  await page.getByRole('button', { name: 'Descartar cambios' }).click()

  const templateDownloadPromise = page.waitForEvent('download')
  await page.getByRole('button', { name: 'Plantilla', exact: true }).click()
  const templateDownload = await templateDownloadPromise
  expect(templateDownload.suggestedFilename()).toBe('nexo-catalog-seed-template.json')
  const templatePath = await templateDownload.path()
  if (!templatePath) throw new Error('Template download path is missing')
  const templatePayload = JSON.parse(await readFile(templatePath, 'utf8')) as { items?: unknown[] }
  expect(templatePayload.items?.length).toBeGreaterThan(0)

  await page.getByLabel('Importar lote de catalogo JSON').setInputFiles({
    name: 'public-catalog.seed.json',
    mimeType: 'application/json',
    buffer: Buffer.from(
      JSON.stringify({
        items: [
          {
            title: 'Moon',
            type: 'movie',
            description: 'Ciencia ficcion contenida y solitaria.',
            releaseYear: 2009,
            genres: ['Ciencia ficcion', 'Drama'],
            tags: ['culto', 'introspectivo'],
            moodTags: ['melancolico'],
          },
        ],
      }),
    ),
  })
  await expect(page.getByText('Seed preparado: 1 nueva / 0 actualizadas')).toBeVisible()
  await expect(page.getByLabel('Seed de catalogo preparado')).toContainText('public-catalog.seed.json')
  await expect(page.getByLabel('Seed de catalogo preparado')).toContainText('1 entradas revisadas antes de tocar el catalogo publico')
  await expect(page.getByRole('heading', { name: 'Moon' })).not.toBeVisible()
  await page.getByRole('button', { name: 'Aplicar lote' }).click()
  await expect(page.getByText('Importadas 1 entradas al catalogo')).toBeVisible()
  await expect(page.getByTestId('session-activity')).toContainText('Seed aplicado')
  await expect(page.getByRole('heading', { name: 'Moon' })).toBeVisible()

  await page.getByRole('button', { name: 'Crear Libros' }).click()
  const editor = page.locator('.item-editor')
  await expect(editor.getByLabel('Tipo')).toHaveValue('book')
  await expect(editor.getByRole('group', { name: 'Medio publico de la entrada' })).toContainText('Libros')
  await expect(editor.getByLabel('Recetas rapidas para Libros')).toContainText('Ideas grandes')
  await expect(editor.getByLabel('Generos predefinidos para Libros')).toContainText('Mitologia')
  await editor.getByLabel('Titulo').fill('Solaris')
  await expect(editor.getByLabel('Curacion rapida')).toContainText('Falta Descripcion')
  await expect(editor.getByTestId('catalog-genre-shortcuts')).toContainText('Generos predefinidos')
  await expect(editor.getByTestId('catalog-genre-shortcuts')).toContainText('Mitologia')
  await editor.getByRole('button', { name: 'Completar minimo' }).click()
  await expect(editor.getByLabel('Descripcion')).toHaveValue(/Solaris combina/)
  await expect(editor.getByLabel('Generos', { exact: true })).toHaveValue('Clasico, Aventura, Mitologia')
  await expect(editor.getByLabel('Tags', { exact: true })).toHaveValue('clasico, epico, literatura')
  await expect(editor.getByLabel('Mood tags')).toHaveValue('denso')
  await expect(editor.getByLabel('Curacion rapida')).toContainText('3/4 listo')
  await editor.getByRole('button', { name: 'Guardar y crear otra' }).click()

  await expect(page.getByText('Solaris guardado en catalogo')).toBeVisible()
  await expect(page.getByTestId('session-activity')).toContainText('Catalogo actualizado')
  await expect(editor.getByLabel('Titulo')).toHaveValue('')
  await editor.getByLabel('Titulo').fill('Dune')
  await editor.getByLabel('Descripcion').fill('Politica, desierto y destino.')
  await editor.getByLabel('Generos predefinidos principales para Libros').getByRole('button', { name: 'Ciencia ficcion' }).click()
  await editor.getByLabel('Sugerencias de tags para Libros').getByRole('button', { name: 'epico' }).click()
  await editor.getByLabel('Sugerencias de tono').getByRole('button', { name: 'denso' }).click()
  await editor.getByRole('button', { name: 'Guardar en catalogo' }).click()

  await expect(page.getByRole('heading', { name: 'Solaris' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Dune' })).toBeVisible()
  await expect(page.getByRole('button', { name: /Pendientes \d+/ })).toBeVisible()
  await page.getByRole('button', { name: /Pendientes/ }).click()
  await expect(page.getByRole('heading', { name: 'Dune' })).toBeVisible()
  await expect(page.getByRole('heading', { name: 'Outer Wilds' })).not.toBeVisible()
  await page.getByLabel('Filtrar catalogo por tipo').selectOption('manhwa')
  await expect(page.getByRole('heading', { name: 'Sin entradas con esos filtros' })).toBeVisible()
  await page.getByRole('button', { name: 'Ver todo el catalogo' }).click()
  await expect(page.getByRole('heading', { name: 'Solaris' })).toBeVisible()
  await page.getByLabel('Ordenar catalogo').selectOption('title')
  await expect(page.getByText(/\d+ de \d+ entradas visibles/)).toBeVisible()
  await expect(page.getByRole('button', { name: 'Editar Solaris' })).toBeVisible()
  await page.getByRole('button', { name: 'Archivar Solaris' }).click()
  await expect(page.getByRole('heading', { name: 'Archivar entrada publica' })).toBeVisible()
  await page.getByRole('button', { name: 'Archivar entrada' }).click()

  await expect(page.getByText('Solaris archivado')).toBeVisible()
  await expect(page.getByTestId('session-activity')).toContainText('Entrada archivada')
  await expect(page.getByRole('button', { name: 'Deshacer archivado' })).toBeVisible()
  await page.getByRole('button', { name: 'Deshacer archivado' }).click()
  await expect(page.getByText('Solaris recuperado en catalogo')).toBeVisible()
  await expect(page.getByTestId('session-activity')).toContainText('Entrada recuperada')
  await expect(page.getByRole('button', { name: 'Editar Solaris' })).toBeVisible()
  await page.getByRole('button', { name: 'Archivar Solaris' }).click()
  await expect(page.getByRole('heading', { name: 'Archivar entrada publica' })).toBeVisible()
  await page.getByRole('button', { name: 'Archivar entrada' }).click()
  await expect(page.getByRole('button', { name: 'Editar Solaris' })).not.toBeVisible()
})

test('moderator can turn an explorer candidate into a public catalog item', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'Explorador', exact: true }).click()
  await page.getByLabel('Buscar en explorador').fill('V Rising')
  await page.getByRole('button', { name: 'Buscar' }).click()

  await expect(page.getByRole('button', { name: 'Crear catalogo V Rising' })).toBeVisible()
  await page.getByRole('button', { name: 'Crear catalogo V Rising' }).click()

  const editor = page.locator('.public-item-editor')
  await expect(editor.getByLabel('Titulo')).toHaveValue('V Rising')
  await expect(editor.getByLabel('Descripcion')).toHaveValue('Candidato de demostracion hasta configurar Firebase Functions.')
  await expect(editor.getByLabel('Tipo')).toHaveValue('movie')

  await editor.getByRole('button', { name: 'Noche palomitas' }).click()
  await expect(editor.getByLabel('Generos', { exact: true })).toHaveValue('Accion, Aventura')
  await expect(editor.getByLabel('Tags', { exact: true })).toHaveValue('palomitas, visual')
  await editor.getByRole('button', { name: 'Guardar en catalogo' }).click()

  await expect(page.getByText('V Rising guardado en catalogo Nexo.')).toBeVisible()
  await page.getByRole('button', { name: 'Curacion' }).click()
  await expect(page.getByRole('heading', { name: 'V Rising' })).toBeVisible()
})

test('delete all requires explicit confirmation', async ({ page }) => {
  await page.goto('/')
  await expect(page.getByTestId('library-grid')).toContainText('Outer Wilds')
  await page.getByRole('button', { name: 'Mas acciones Mass Effect Legendary Edition' }).click()
  await page.getByRole('menuitem', { name: 'Borrar Mass Effect Legendary Edition' }).click()
  await expect(page.getByRole('dialog', { name: 'Borrar entrada' })).toContainText('Mass Effect Legendary Edition')
  await page.getByRole('button', { name: 'Borrar entrada' }).click()
  await expect(page.getByTestId('library-grid')).not.toContainText('Mass Effect Legendary Edition')
  await expect(page.getByRole('button', { name: 'Deshacer borrado' })).toBeVisible()
  await page.getByRole('button', { name: 'Deshacer borrado' }).click()
  await expect(page.getByText('Mass Effect Legendary Edition recuperado en Biblioteca')).toBeVisible()
  await expect(page.getByTestId('library-grid')).toContainText('Mass Effect Legendary Edition')

  await page.getByRole('button', { name: 'Borrar todo' }).click()
  await expect(page.getByRole('heading', { name: 'Borrar toda la biblioteca' })).toBeVisible()
  await expect(page.getByRole('button', { name: 'Borrar todo' }).last()).toBeDisabled()

  await page.getByLabel('Confirmacion').fill('BORRAR')
  await page.getByRole('button', { name: 'Borrar todo' }).last().click()

  await expect(page.getByText('Tu biblioteca ha sido borrada')).toBeVisible()
  await expect(page.getByText('Outer Wilds')).not.toBeVisible()
  await expect(page.getByRole('button', { name: 'Deshacer borrado total' })).toBeVisible()
  await page.getByRole('button', { name: 'Deshacer borrado total' }).click()
  await expect(page.getByText(/\d+ entradas recuperadas en Biblioteca/)).toBeVisible()
  await expect(page.getByTestId('library-grid')).toContainText('Outer Wilds')
})

test('launch screens have no serious accessibility violations', async ({ page }) => {
  await page.goto('/')
  const results = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa']).analyze()
  const seriousViolations = results.violations.filter((violation) => ['serious', 'critical'].includes(violation.impact ?? ''))

  expect(seriousViolations).toEqual([])
})
